name: Package Azure Function App

on:
  push:
    paths:
      - 'function-app/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies to .python_packages/lib/site-packages/
        working-directory: function-app
        run: |
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt --target .python_packages/lib/site-packages

      - name: Create deployment.zip outside source dir
        run: |
          cd function-app
          zip -r ../deployment.zip . -x "*.git*" "*.github*" "__pycache__/*" "deployment.zip"

      - name: Generate timestamped version tag
        id: version
        run: echo "tag=function-app-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          files: deployment.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update WEBSITE_RUN_FROM_PACKAGE in functionapp_azuredeploy.json
        run: |
          sed -i 's#https://github.com/.*/deployment.zip#https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/deployment.zip#g' function-app/functionapp_azuredeploy.json

      - name: Commit updated Azure deploy JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add function-app/functionapp_azuredeploy.json
          git commit -m "Update WEBSITE_RUN_FROM_PACKAGE to ${{ steps.version.outputs.tag }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
